name: SU2 Validation Pipeline - Streamlined

on:
  workflow_dispatch:
    inputs:
      category:
        description: 'Validation Case Category'
        required: true
        type: choice
        options:
          - Basic
          - Extended
      case_name:
        description: 'Validation Case Name (e.g., 2D Mixing Layer)'
        required: true
        type: string
      case_code:
        description: 'Validation Case Code (e.g., 2DML)'
        required: true
        type: string
      solver:
        description: 'Solver Type'
        required: false
        type: choice
        options:
          - RANS
          - EULER
          - NAVIER_STOKES
        default: RANS
      mach_number:
        description: 'Mach Number'
        required: false
        type: string
        default: '0.12'
      aoa:
        description: 'Angle of Attack (degrees)'
        required: false
        type: string
        default: '0'
      cfl_number:
        description: 'CFL Number'
        required: false
        type: string
        default: '100.0'
      iterations:
        description: 'Number of Iterations'
        required: false
        type: string
        default: '100000'
      turb_model:
        description: 'Turbulence Model'
        required: false
        type: choice
        options:
          - SA
          - SST
          - NONE
        default: SA
      custom_config:
        description: 'Custom Config (JSON format: {"PARAM":"value"})'
        required: false
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SU2 Main Repo
        uses: actions/checkout@v4
        with:
          path: su2-main

      - name: Checkout VandV Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/SU2-VandV
          path: su2-vandv
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Configuration Files
        run: |
          CATEGORY="${{ inputs.category }}"
          CASE_CODE="${{ inputs.case_code }}"
          CONFIG_PATH="su2-main/VandV/$CATEGORY/$CASE_CODE/config.cfg"
          
          # Create updated config from template
          cp su2-main/template_config.cfg "$CONFIG_PATH"
          
          # Load default parameters from JSON
          python3 -c "
import json
with open('su2-main/config_defaults.json') as f:
    defaults = json.load(f)
for key, value in defaults.items():
    print(f'{key}={value}')
" > all_params.txt
          
          # Update main configuration parameters
          if [ -n "${{ inputs.solver }}" ]; then
            sed -i "s/^SOLVER=.*/SOLVER= ${{ inputs.solver }}/" "$CONFIG_PATH"
          fi
          if [ -n "${{ inputs.turb_model }}" ]; then
            sed -i "s/^KIND_TURB_MODEL=.*/KIND_TURB_MODEL= ${{ inputs.turb_model }}/" "$CONFIG_PATH"
          fi
          if [ -n "${{ inputs.mach_number }}" ]; then
            sed -i "s/^MACH_NUMBER=.*/MACH_NUMBER= ${{ inputs.mach_number }}/" "$CONFIG_PATH"
          fi
          if [ -n "${{ inputs.aoa }}" ]; then
            sed -i "s/^AOA=.*/AOA= ${{ inputs.aoa }}/" "$CONFIG_PATH"
          fi
          if [ -n "${{ inputs.cfl_number }}" ]; then
            sed -i "s/^CFL_NUMBER=.*/CFL_NUMBER= ${{ inputs.cfl_number }}/" "$CONFIG_PATH"
          fi
          if [ -n "${{ inputs.iterations }}" ]; then
            sed -i "s/^ITER=.*/ITER= ${{ inputs.iterations }}/" "$CONFIG_PATH"
          fi
          
          # Apply all default parameters from JSON
          while IFS='=' read -r key value; do
            if [ -n "$key" ] && [ -n "$value" ]; then
              sed -i "s/^$key=.*/$key= $value/" "$CONFIG_PATH"
            fi
          done < all_params.txt
          
          # Process custom config if provided (overrides defaults)
          if [ -n "${{ inputs.custom_config }}" ]; then
            echo "Processing custom configuration..."
            echo '${{ inputs.custom_config }}' | python3 -c "
import json
import sys
try:
    config = json.load(sys.stdin)
    for key, value in config.items():
        print(f'{key}={value}')
except:
    pass
" > custom_params.txt
            
            while IFS='=' read -r key value; do
              if [ -n "$key" ] && [ -n "$value" ]; then
                sed -i "s/^$key=.*/$key= $value/" "$CONFIG_PATH"
                echo "Updated $key = $value"
              fi
            done < custom_params.txt
          fi

      - name: Copy Config to All Mesh Folders
        run: |
          CATEGORY="${{ inputs.category }}"
          CASE_CODE="${{ inputs.case_code }}"
          MAIN_PATH="su2-main/VandV/$CATEGORY/$CASE_CODE"
          CONFIG_PATH="$MAIN_PATH/config.cfg"
          
          # Copy updated config to all mesh folders
          for mesh_folder in "$MAIN_PATH"/*; do
            if [ -d "$mesh_folder" ] && [ "$(basename "$mesh_folder")" != "." ] && [ "$(basename "$mesh_folder")" != ".." ]; then
              cp "$CONFIG_PATH" "$mesh_folder/"
              echo "Copied config to $(basename "$mesh_folder")"
            fi
          done

      - name: Copy Files from VandV Repo
        run: |
          CATEGORY="${{ inputs.category }}"
          CASE_CODE="${{ inputs.case_code }}"
          VANDV_PATH="su2-vandv/VandV/$CATEGORY/$CASE_CODE"
          MAIN_PATH="su2-main/VandV/$CATEGORY/$CASE_CODE"
          
          # Copy restart and mesh files from VandV repo to main repo
          for mesh_folder in "$VANDV_PATH"/*; do
            if [ -d "$mesh_folder" ]; then
              folder_name=$(basename "$mesh_folder")
              target_folder="$MAIN_PATH/$folder_name"
              
              if [ -d "$target_folder" ]; then
                echo "Copying files to $target_folder"
                
                # Copy restart file
                if [ -f "$mesh_folder/restart.dat" ]; then
                  cp "$mesh_folder/restart.dat" "$target_folder/"
                fi
                
                # Copy mesh file
                find "$mesh_folder" -name "*.su2" -exec cp {} "$target_folder/" \;
              fi
            fi
          done

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake python3 python3-pip
          sudo apt-get install -y libopenmpi-dev openmpi-bin
          pip3 install numpy matplotlib pandas

      - name: Build SU2
        run: |
          cd su2-main
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          sudo make install

      - name: Run Automation Script
        run: |
          cd su2-main/VandV/${{ inputs.category }}/${{ inputs.case_code }}
          if [ -f "../../Automation.py" ]; then
            python3 ../../Automation.py
          else
            echo "::warning::Automation.py not found, skipping simulation"
          fi

      - name: Generate Plots
        run: |
          cd su2-main/VandV/${{ inputs.category }}/${{ inputs.case_code }}
          if [ -f "Plot.py" ]; then
            python3 Plot.py
          else
            echo "::warning::Plot.py not found, skipping plot generation"
          fi

      - name: Collect Results
        run: |
          mkdir -p results
          find su2-main/VandV/${{ inputs.category }}/${{ inputs.case_code }} -name "*.csv" -exec cp {} results/ \; 2>/dev/null || true
          find su2-main/VandV/${{ inputs.category }}/${{ inputs.case_code }} -name "*.vtu" -exec cp {} results/ \; 2>/dev/null || true
          find su2-main/VandV/${{ inputs.category }}/${{ inputs.case_code }} -name "*.png" -exec cp {} results/ \; 2>/dev/null || true
          find su2-main/VandV/${{ inputs.category }}/${{ inputs.case_code }} -name "*.jpg" -exec cp {} results/ \; 2>/dev/null || true

      - name: Upload Results as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: su2-validation-results-${{ inputs.case_code }}
          path: results/

      - name: Deploy to Website Repo
        if: success()
        run: |
          # Clone website repo
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/SU2-Website.git website
          cd website
          
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Create new branch with case name
          BRANCH_NAME="${{ inputs.case_name }}"
          git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"
          
          # Create folder structure
          mkdir -p "vandv_files/${{ inputs.case_name }}"
          
          # Copy plot files to website repo
          find ../results -name "*.png" -exec cp {} "vandv_files/${{ inputs.case_name }}/" \; 2>/dev/null || true
          find ../results -name "*.jpg" -exec cp {} "vandv_files/${{ inputs.case_name }}/" \; 2>/dev/null || true
          
          # Commit and push if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Add validation results for ${{ inputs.case_name }}"
            git push origin "$BRANCH_NAME"
          else
            echo "No changes to commit"
          fi