name: Update Config Options

on:
  workflow_dispatch:
    inputs:
      case_code:
        description: "Validation Case Code"
        required: true
        type: string

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: config-data
          path: artifacts/

      - name: Read config metadata
        id: read-config
        run: |
          echo "CASE_CODE=$(cat artifacts/case_code.txt)" >> $GITHUB_ENV
          echo "CONFIG_PATH=$(cat artifacts/config_path.txt)" >> $GITHUB_ENV

      - name: Show extracted config keys
        run: |
          echo "Config keys:"
          cat artifacts/config_options.json | jq -r '.[]'

      - name: Inject placeholder values into config file
        run: |
          echo "Updating config file with placeholders..."
          cp artifacts/original_config.cfg "$CONFIG_PATH"

          jq -r '.[]' artifacts/config_options.json | while read key; do
            placeholder="REPLACE_ME_FOR_${key}"
            if grep -q "^$key *=.*" "$CONFIG_PATH"; then
              sed -i "s/^$key *=.*/$key= $placeholder/" "$CONFIG_PATH"
            else
              echo "$key= $placeholder" >> "$CONFIG_PATH"
            fi
          done

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "$CONFIG_PATH"
          git commit -m "Updated config with placeholders for $CASE_CODE"
          git push
