name: Update Config Options

on:
  workflow_dispatch:
    inputs:
      case_code:
        description: "Validation Case Code"
        required: true
        type: string

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Load cached config data
        id: load-cache
        run: |
          CASE_CODE="${{ inputs.case_code }}"
          CACHE_DIR=".ci/cache/$CASE_CODE"

          if [ ! -f "$CACHE_DIR/original_config.cfg" ]; then
            echo "::error::Cached config not found for $CASE_CODE"
            exit 1
          fi

          CONFIG_PATH=$(cat "$CACHE_DIR/config_path.txt")

          echo "CONFIG_PATH=$CONFIG_PATH" >> $GITHUB_ENV
          echo "CASE_CODE=$CASE_CODE" >> $GITHUB_ENV

          cp "$CACHE_DIR/original_config.cfg" "$CONFIG_PATH"
          jq -r '.[]' "$CACHE_DIR/config_options.json" > config_keys.txt

      - name: Update config with placeholders
        run: |
          echo "Updating: $CONFIG_PATH"
          while read key; do
            placeholder="REPLACE_ME_FOR_${key}"
            if grep -q "^$key *=.*" "$CONFIG_PATH"; then
              sed -i "s/^$key *=.*/$key= $placeholder/" "$CONFIG_PATH"
            else
              echo "$key= $placeholder" >> "$CONFIG_PATH"
            fi
          done < config_keys.txt

      - name: Commit updated config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add "$CONFIG_PATH"
          git commit -m "Updated config for $CASE_CODE"
          git push
